name: Backend CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Show Node.js version
        run: node -v

      - name: Run backend tests
        run: npm test --verbose

      - name: Set up environment variables
        run: echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
